config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    path: '',
    path_names: { sign_in: 'login', sign_out: 'logout', registration: 'signup' },
    controllers: { sessions: 'sessions', registrations: 'registrations', passwords: 'passwords' }

  root to: 'home#index'

  namespace :api do
    namespace :v1 do
      resources :events, only: [:index, :create, :show, :update] do
        resources :user_event_responses, only: [:create]
      end

      resources :friendship_requests, only: [:index, :create] do
        member do
          post 'confirm', 'reject'
        end
      end

      resources :users, only: [:show, :index]

      resources :friendships, only: [:index]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :events_artists
  has_many :events, through: :events_artists

end

# == Schema Information
#
# Table name: artists
#
#  id          :integer         not null, primary key
#  name        :string
#  spotify_uri :string
#  uuid        :string
#

app/models/event.rb
class Event < ApplicationRecord
  has_many :user_event_responses
  has_many :users, through: :user_event_responses

  scope :today_onwards, -> { where("date_time >= ?", Date.today.beginning_of_day) }
  scope :hosted_by,
        -> (user_id) { joins(:user_event_responses).where(user_event_responses: { user_id: user_id, host: true }) }

  validates :name, presence: true
  validates :date_time, presence: true

  # Get the hosts for the event
  def hosts
    users.merge(UserEventResponse.hosting)
  end

end

app/models/event_status.rb
class EventStatus < ApplicationRecord
  belongs_to :user
  belongs_to :event

  STATUSES =  [:interested, :going, :cant_go, :not_interested, :no_status]

  #TODO: validate status
  # TODO: validate user has access to associated event
end

app/models/events_artist.rb
class EventsArtist < ActiveRecord::Base
  belongs_to :events
  belongs_to :artist

end

# == Schema Information
#
# Table name: events_artists
#
#  id        :integer         not null, primary key
#  event_id  :integer         not null
#  artist_id :integer         not null
#  headliner :boolean         default("false")
#

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

end

app/models/friendship_request.rb
class FriendshipRequest < ApplicationRecord
  belongs_to :pending_friend, foreign_key: :pending_friend_id, class_name: 'User'
  belongs_to :requesting_friend, foreign_key: :requesting_friend_id, class_name: 'User'

  def accept!
    FriendshipRequest.transaction do
      User.find(pending_friend_id) && User.find(requesting_friend_id)
      Friendship.create!(user_id: requesting_friend_id, friend_id: pending_friend_id)
      Friendship.create!(user_id: pending_friend_id, friend_id: requesting_friend_id)
      self.destroy!
    end
  end

end

app/models/jwt_blacklist.rb
class JWTBlacklist < ApplicationRecord
  include Devise::JWT::RevocationStrategies::Blacklist
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_event_responses, dependent: :destroy
  has_many :events, through: :user_event_responses
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships, class_name: 'User'

  has_many :pending_friendship_requests, foreign_key: :requesting_friend_id,
           class_name: 'FriendshipRequest', dependent: :destroy
  has_many :pending_friends, through: :pending_friendship_requests, source: :pending_friend

  has_many :requesting_friendship_requests, foreign_key: :pending_friend_id,
           class_name: 'FriendshipRequest', dependent: :destroy
  has_many :requesting_friends, through: :requesting_friendship_requests, source: :requesting_friend

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :jwt_authenticatable, :registerable, :recoverable, :rememberable, :trackable,
         :validatable, :timeoutable, jwt_revocation_strategy: JWTBlacklist
  
  has_one_attached :profile_pic
end

app/models/user_event_response.rb
class UserEventResponse < ApplicationRecord
  belongs_to :user
  belongs_to :event

  scope :hosting, -> { where(host: true) }

  STATUSES =  [:interested, :going, :cant_go, :not_interested, :no_status]

  validates :status, inclusion: { in: STATUSES.map(&:to_s) }

  # TODO: validate user has access to associated event
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  has_many :events

end

# == Schema Information
#
# Table name: venues
#
#  id          :integer         not null, primary key
#  name        :string
#  description :text
#  address     :string
#

app/controllers/api/events_controller.rb
class Api::EventsController < ApiController
  def index
    @events = Event.all
    json_response(@events)
  end

  def create
    event = Event.create!(event_params)
    json_response(event)
  end

  def show
    json_response(Event.find(params[:id]))
  end

  private

  def event_params
    params.permit(:name, :date_time, :description, :event_link, :location)
  end
end

app/controllers/api/v1/events_controller.rb
class API::V1::EventsController < API::V1::APIController

  # @param page - the next page of events to request
  def index
    @events = Event.all.order(:date_time).today_onwards.page(params[:page].to_i || 1)
    json_response(@events)
  end

  def create
    event = Event.new(event_params)
    event.user_event_responses.new(user: current_user, host: true, status: :going)
    event.save!

    json_response([event])
  end

  def show
    # TODO: must have permission for this event
    json_response(Event.find(params[:id]))
  end

  def update
    json_response(Event.hosted_by(current_user.id).find_by!(id: params[:id]).update!(event_params))
  end

  private

  def event_params
    params.permit(:name, :date_time, :description, :event_link, :location)
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::API
  # API only controllers inherit from here instead of application controller
  include Response
  include ExceptionHandler

  before_action :authenticate_user!
end

app/controllers/events_controller.rb
class EventsController < ApiController
  def index
    @events = Event.all
    json_response(@events)
  end

  def create
    event = Event.create!(event_params.merge!(user: current_user))
    json_response([event])
  end

  private

  def event_params
    params.permit(:name, :date_time, :description, :event_link, :location)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

  def new
  end

  def index
  end

  def create
  end

  private

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.haml
.container-fluid
  %h1 Edit Event Page
  = form_for(@event) do |e|
    = e.label(:name)
    = e.text_field(:name, value: @event.name)
    %br
    = e.label(:headlining_artist)
    = e.label(:opening_artists)

app/views/events/index.html.haml
%a{ href: new_event_url } Create a New Event

%h1 All Events


%br

.events_scroll
  - last_date = nil
  - @events.each do |event|
    - if event.date != last_date
      - last_date = event.date
      .date= last_date
    %table.event_row
      %tr
        %td.event_column
          = form_for(event, url: edit_event_url(event.id), method: :get, html: { class: :edit_event_form }) do
            - color = cycle('even', 'odd')
            .event{ class: color, id: event.id }
              %table.events_display
                %tr
                  %td
                    .value#created_by= event.created_by.name
                  %td
                    .value#name= event.display_name
                  %td
                    .value#venue= event.venue.try(:name) || 'N/A'
        %td.select_column
          = form_for(event, url: event_url(event.id), method: :put, html: { class: :update_status_form }) do
            = event.id
            .select_buffer
              = hidden_field :user_statuses_for_events, :event_id, value: event.id
              .styled_select
                %select.user_statuses_for_events_status{ name: 'user_statuses_for_events[status]', id: event.id }
                  - selected = event.user_statuses_for_events.find_by(user_id: @current_user.id).try(:status) || 2
                  = options_for_select(UserStatusesForEvent::STATUSES.to_a, selected)



:javascript
  initEventHover();
  initSubmitEvent();
  initStatusWatcher();

app/views/events/new.haml
.container
  %h1 Create a New Event

  .form#new_event
    = form_for @event do |f|
      %label Name
      .field
        = f.text_field :name
      %label Artist Name
      .field
        = text_field :artist, :name
      %label Venue
      .field
        = text_field :venue, :name
      %label Date/Time
      .field
        = f.date_field :date
      .field
        = f.time_field :start_time
      %label Description
      .field
        = f.text_area :description

      %hr
      %button Submit Form

app/views/events/show.haml
.container
  %h1 Event Details Page